### ISSUE TITLE
Merge complete: Follow up work

### ISSUE THREAD

**Issue by akidhruv** [Balaras-Group/MAE-6225#24]
Dear all,

Please ignore previous notifications from me regarding fixing the issues with your pull requests. Everything has been corrected and your work has been integrated into the develop branch.

- I had to create new branches for some of you, they have been personally notified.

- Please pull latest changes from individual branches before doing any new work, I had to do some book keeping in individual branches.

- Going forward I would recommend deleting the old branches that have your name if you don't need the work.

you can delete a local branch by typing
git branch -D <branch_name>

and a remote branch by typing
git push origin --D <branch_name>

you can sync deleted branches with remote by typing
git remote prune origin

Your work is incorporated in the develop branch under MAE-6225/mae6225/ins/

Feel free to comment on this issue with questions.

Alternatively, if you would like me to delete your name branch from the remote please comment the name of branch that you want to remove

**Comment by RongyuChu** [comment]
Hi, Dear Akash

I know that I have to do the correction part for the code. But since I did
not attend the last class, I am not pretty sure which part of the note
should I looking at. Can you help me about this? Thank you.

Best regards

Rongyu Chu

**Comment by akidhruv** [comment]
@RongyuChu I don't have the notes with me. But, the corrector step is the one which you apply after solving the pressure Poisson solver. If you want to know where it is in the notes, please send an email to Prof. Balaras.

**Comment by RongyuChu** [comment]
Hi, Dear Akash

Do you have time this afternoon or tomorrow before the class ? I still have
some part confused about the correction part and want to ask you about
that. Thank you so much.

Best

Rongyu Chu

**Comment by akidhruv** [comment]
@RongyuChu Come anytime after 11:30 am.
