### ISSUE TITLE
Incompressible Navier Stokes: Follow up work

### ISSUE THREAD

**Issue by akidhruv** [Balaras-Group/MAE-6225#30]
Dear all,

I have fixed the bugs in the development branch. will push the updates with a test case soon. I also deleted the test branches since we no longer need them, to sync remote and your local repository please execute following commands:

- Undo any local changes you made
`git checkout <filename>`

- Switch to the development branch
`git checkout develop`

- Delete the test branch on your local repo
`git branch -D <branch-name>`

- Sync with remote
`git remote prune origin`

I will send a note once I have pushed updates.

Akash

**Comment by akidhruv** [comment]
Dear all,

Incompressible Navier Stokes updates have been merged to the master branch. You can pull the changes and get a head start on Taylor-Green Vortex problem. See the files under examples/ins for a Lid-Driven cavity sample. You will have to create additional subroutines under simulation.py for analytical solutions. Feel free to reach out with your questions. See you Friday

Akash

**Comment by akidhruv** [comment]
Taylor Green Vortex and Lid Driven Cavity examples available now

**Comment by akidhruv** [comment]
@HUDamon96 @RongyuChu @alexuscamero @egregorio @djennings60 @chenkuangxu 

Please name your notebooks as ins_rk3.ipynb and ins_ab2.ipynb to test your subroutines. Make your you create new files instead of changing the ones already present.

**Comment by RongyuChu** [comment]
@akidhruv 
Hi, Dear Akash

When we calculate l2 norm, should we calculate it at x face ? What about the y face ? Thank you.

**Comment by RongyuChu** [comment]
@akidhruv 

And another problem is when is try 120*120 with cg method, all three methods doesn't work.

**Comment by akidhruv** [comment]
@RongyuChu Calculate norm for both u and v velocity on xface and yface grid respectively and try a smaller step size for 120 x 120 grid

**Comment by RongyuChu** [comment]
@akidhruv Do I need to keep the time step size same to compare the l2_norm ? Because I have to smaller the time step size when the mesh is not coarse. (The original one won't work even for 90*90 of AB2 method).

**Comment by akidhruv** [comment]
@RongyuChu, you will **need** to reduce time step with your grid refinement to match the CFL condition. For spatial accuracy tests, make sure you **reduce your time-step by a constant factor** with your grid refinement. The rule of thumb is that **if you increase your grid refinement by 2 then you should reduce time step by four**. 

For temporal accuracy, make sure to use the same time-step for all the methods. **Since AB2 requires smallest time-step, you should use that time-step for all the methods**.

Does this help?

**Comment by RongyuChu** [comment]
Dear all,

We can compare the L_infinity_norm instead of L2_norm for the accuracy. To do that, you just need to add code of L_infinity_norm into your grid.py file. The code is below:

def get_linfinity_norm(self, eror):
        """Compute the L infinity norm for a given variable.

        Arguments
        ---------
        eror : string
            Name of the grid variable for which norm is desired

        Returns
        -------
        linfinity_norm : float
            The Linfinity-norm.

        """
        i_eror = self.get_variable_indices(eror)

        linfinity_norm = numpy.amax(self.data[:, :, i_eror])

        return linfinity_norm

**Comment by RongyuChu** [comment]
@akidhruv I found I could not do the pull request because I can only choose to compare develop and master branch. so I just posted the code here.
